apiVersion: v1
kind: Service
metadata:
  name: keycloak-internal
  labels:
    app: keycloak-internal
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
