apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
data:
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: ZFo1ajk0cHZ3TQ==

